sudo: false
language: node_js

node_js:
  - '8'

matrix:
  fast-finish: true     # https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8

addons:
  chrome: stable
  firefox: "45.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm prune
  - npm set progress=false

install:
  - npm install

before_script:
  # Allow Firefox to run in virtual frame buffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  #- npm run pre-release #disabled due to Chrome headless not working (even locally)
  - npm run verify
  - npm run build

after_success:
  #- npm run upload-coverage  # disabled due to tests being disabled
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    recipients:
      - u_glow@hotmail.com
